# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - handinhand-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore
        run: dotnet restore
        working-directory: backend

      - name: Build
        run: dotnet build -c Release --no-restore
        working-directory: backend

      - name: Publish
        run: dotnet publish -c Release -o ${{github.workspace}}/publish --no-build
        working-directory: backend

      - uses: actions/upload-artifact@v4
        with:
          name: backend
          path: ${{github.workspace}}/publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D4E38D39D6754643930213D0F2B6FC48 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_51692EB451F04C209193D1054864D109 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_48290C351BDA489381518DEEB6716283 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'handinhand-api'
          slot-name: 'Production'
          package: ${{github.workspace}}/publish
          